# Paths
jsonld_dir: data/rdf_files
persist_directory: "src/nomad_compass/chatbot_backend/data/vector_db/.chroma_sn"

# Models (available via HU Ollama/Open WebUI)
ollama_base_url: "http://172.28.105.142:11434"   # keep as-is if that endpoint works for you
embedding_backend: "hf"
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
chat_model: "gpt-oss:20b"                         # alt: "deepseek-r1:32b"
reasoning: false                                  # true only if using deepseek-r1 reasoning

# RAG settings
chunk_size: 1000
chunk_overlap: 200
k: 4

vocabulary_path: "src/nomad_compass/chatbot_backend/vocabulary.json"
